apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-generator-test
  namespace: openshift-gitops
spec:
  destination:
    namespace: rhacm-policy
    server: local-cluster
  project: default
  source:
    path: compliance-operator
    repoURL: https://github.com/mtartara/policy-generator-acm.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
