apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-compliance-operator
policyDefaults:
  namespace: rhacm-policies
  remediationAction: enforce
  placement:
    name: placement-devel-test
    clusterSelectors:
      env: test
policies:
  - name: install-compliance-operator
    manifests:
      - path: compliance-operator.yaml

